<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fig</string>
		<string>tikz</string>
	</array>
	<key>name</key>
	<string>TikZ</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>((\\)(clip|coordinate|draw|fill(draw)?|node|path|shade(draw)?|useasboundingbox))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.draw.latex.tikz</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.latex.tikz</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.latex.tikz</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.draw.latex.tikz</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>and|at|circle|controls|coordinate|grid|rectangle</string>
					<key>name</key>
					<string>keyword.control.tikz</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\s	]*\\(clip|coordinate|draw|fill(draw)?|node|path|shade(draw)?|useasboundingbox|end)</string>
					<key>name</key>
					<string>invalid.illegal.tikz</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.latex.tikz</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.latex.tikz</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.latex.tikz</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)([^\]]+)(\])</string>
					<key>name</key>
					<string>meta.parameter.tikz</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameter.begin.latex.tikz</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.latex.tikz</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.latex.tikz</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\()([^\)]+)(\))</string>
					<key>name</key>
					<string>meta.parameter.tikz</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.begin.latex.tikz</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.arguments.end.latex.tikz</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.tex.latex</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.tex.latex</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tex.latex.tikz</string>
	<key>uuid</key>
	<string>f25f4527-1ff2-478f-bd06-e34974f0387e</string>
</dict>
</plist>
